/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GestionDeProductosEmpleadoV1;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.util.List;

/**
 *
 * @author gerardo
 */
public class FrmCredenciales extends javax.swing.JInternalFrame {

    DefaultTableModel modelo1;
    AdministrarCredenciales admCredenciales;
    private String fechaActual;

    /**
     * Creates new form FrmCredenciales
     */
    public FrmCredenciales() {
        initComponents();
        String[] columna = {"Nombre", "Apellido", "ID", "Contraseña", "Cargo"};
        modelo1 = new DefaultTableModel(columna, 0);
        tblCredencial.setModel(modelo1);
        admCredenciales = new AdministrarCredenciales();
        establecerFechaActual();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblTitulo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        btnEliminarUsuario = new javax.swing.JButton();
        btnAgregarUsuario = new javax.swing.JButton();
        txtFechaDeContratacion = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCredencial = new javax.swing.JTable();
        cbCargo = new javax.swing.JComboBox<>();
        btnConsultar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setClosable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblTitulo.setText("Credenciales");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre:"));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 41, 97, -1));

        txtID.setBorder(javax.swing.BorderFactory.createTitledBorder("ID:"));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 100, 97, -1));

        txtApellido.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellido:"));
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 41, 94, -1));

        txtContraseña.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña:"));
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 100, 94, -1));

        btnEliminarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-minus-48.png"))); // NOI18N
        btnEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 60, 40));

        btnAgregarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-add-50.png"))); // NOI18N
        btnAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 60, 40));

        txtFechaDeContratacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de creación:"));
        txtFechaDeContratacion.setEnabled(false);
        getContentPane().add(txtFechaDeContratacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 159, 197, -1));

        tblCredencial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblCredencial);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 212, -1, -1));

        cbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccionar-", "Administrador", "Empleado" }));
        cbCargo.setBorder(javax.swing.BorderFactory.createTitledBorder("Cargo:"));
        getContentPane().add(cbCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 160, 70));

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-question-48.png"))); // NOI18N
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 60, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/20250618_1047_Bakery Pattern Delight_simple_compose_01jy1vhbhxejw94jsehtxkgmp1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void establecerFechaActual() {
        LocalDate fecha = LocalDate.now();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String fechaHoy = fecha.format(formato);
        txtFechaDeContratacion.setText(fechaHoy);
    }

    private void mostrarTabla() {
        modelo1.setRowCount(0);
        List<PoseeCredenciales> listaCredenciales = admCredenciales.obtenerCredenciales();
        for (PoseeCredenciales p : listaCredenciales) {
            Object[] fila = {p.getNombre(), p.getApellido(), p.getId(), p.getContraseña(), p.getCargo()};
            modelo1.addRow(fila);
        }
    }

    private void limpiarDatoDespuesDeAgregar() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtID.setText("");
        txtContraseña.setText("");
        txtFechaDeContratacion.setText("");
        cbCargo.setSelectedIndex(0);
    }

    private void escribirTxt() {
        String superUsuario;
        if (cbCargo.getSelectedItem().equals("Administrador")) {
            superUsuario = "true";
        } else {
            superUsuario = "false";
        }
        try (BufferedWriter bw = new BufferedWriter(new FileWriter("/Users/gerardo/Desktop/OneDrive/2025/Code/Java/Aplicacion Proyecto Final/src/GestionDeProductosEmpleadoV1/usuarios.txt", true))) {
            bw.newLine();
            bw.write(txtID.getText() + "," + txtContraseña.getText() + "," + superUsuario);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al escribir el archivo");
        }
        JOptionPane.showMessageDialog(this, "Se agrego correctamente");
    }
    private void btnAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuarioActionPerformed

        PoseeCredenciales newUsuario = null;

        try {
            if (cbCargo.getSelectedItem().equals("Administrador")) {
                newUsuario = new Administrador(
                        txtID.getText(),
                        txtNombre.getText(),
                        txtApellido.getText(),
                        0
                );
            } else if (cbCargo.getSelectedItem().equals("Empleado")) {
                newUsuario = new Empleado(
                        cbCargo.getSelectedItem().toString(),
                        0,
                        txtID.getText(),
                        txtNombre.getText(),
                        txtApellido.getText(),
                        0
                );
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Algún parámetro no está bien definido, por favor revisa.");
            return; // Importante: salir si hubo error
        }

        if (newUsuario == null) {
            JOptionPane.showMessageDialog(this, "Selecciona un cargo válido.");
            return;
        }

        if (admCredenciales.noEstaCompleto(newUsuario)) {
            JOptionPane.showMessageDialog(this, "Falta algún parámetro por llenar, por favor revisa los campos.");
            return;
        }
        newUsuario.setContraseña(txtContraseña.getText());
        boolean agregado = admCredenciales.añadirCredencial(newUsuario);
        if (agregado) {
            escribirTxt();
            mostrarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Ya existe alguien con el mismo ID.");
        }

        limpiarDatoDespuesDeAgregar();
    }//GEN-LAST:event_btnAgregarUsuarioActionPerformed

    private void btnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioActionPerformed
        int filaSeleccionada = tblCredencial.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor seleccione una fila");
        } else {
            admCredenciales.eliminarCredencial(filaSeleccionada);
            JOptionPane.showMessageDialog(this, "Eliminado correctamente");
            mostrarTabla();
        }
    }//GEN-LAST:event_btnEliminarUsuarioActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        String inputId = JOptionPane.showInputDialog(null, "Ingrese ID:");
        PoseeCredenciales poseeCredenciales = admCredenciales.buscar(inputId);
        if (poseeCredenciales != null) {

            JOptionPane.showMessageDialog(this, poseeCredenciales.toString());
        } else {
            JOptionPane.showMessageDialog(null, "Usuario no encontrado con ID: " + inputId, "No encontrado", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarUsuario;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JComboBox<String> cbCargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblCredencial;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtFechaDeContratacion;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
