/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GestionDeProductosEmpleadoV1;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.stream.Collectors;

/**
 *
 * @author gerardo
 */
public class FrmEmpleado extends javax.swing.JInternalFrame {

    DefaultTableModel modelo;
    Empleado empleado;
    AdministrarEmpleado admEmpleado;

    /**
     * Creates new form FrmEmpleado
     */
    public FrmEmpleado() {
        initComponents();
        String[] columna = {"ID", "Nombre", "Apellido", "Pago por hora", "Cargo", "Horas extras", "Salario final", "Cansancio"};
        modelo = new DefaultTableModel(columna, 0);
        tblEmpleado.setModel(modelo);

        admEmpleado = new AdministrarEmpleado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtPagoPorHora = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        txtHorasExtras = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleado = new javax.swing.JTable();
        txtId = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 204, 204));
        lblTitulo.setText("Gestion de Personal");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 330, -1));

        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre:"));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 119, 50));

        txtApellido.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellido:"));
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 119, 50));

        txtPagoPorHora.setBorder(javax.swing.BorderFactory.createTitledBorder("Pago por hora:"));
        getContentPane().add(txtPagoPorHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 119, 50));

        txtCargo.setBorder(javax.swing.BorderFactory.createTitledBorder("Cargo:"));
        getContentPane().add(txtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 119, -1));

        txtHorasExtras.setBorder(javax.swing.BorderFactory.createTitledBorder("Horas extras:"));
        getContentPane().add(txtHorasExtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 119, -1));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-add-50.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 60, -1));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-minus-48.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 60, -1));

        tblEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEmpleado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 204, 600, -1));

        txtId.setBorder(javax.swing.BorderFactory.createTitledBorder("ID:"));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 119, -1));

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-question-48.png"))); // NOI18N
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, -1));

        btnOrdenar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-sort-50.png"))); // NOI18N
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });
        getContentPane().add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Gemini_Generated_Image_fcnbtxfcnbtxfcnb.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 650));

        setBounds(0, 0, 624, 673);
    }// </editor-fold>//GEN-END:initComponents
    private void limpiarDespuesDeAgregar() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtCargo.setText("");
        txtHorasExtras.setText("");
        txtPagoPorHora.setText("");
        txtId.setText("");
    }

    private void mostrarTabla() {
        modelo.setRowCount(0);
        List<Empleado> lista = admEmpleado.obtenerEmpleados();
        for (Empleado em : lista) {
            Object[] fila = {em.getId(), em.getNombre(), em.getApellido(), em.getPagoPorHora(), em.getCargo(), em.getHorasExtras(), em.calcularSalarioFinal(), em.getNivelCansancio()};
            modelo.addRow(fila);
        }
    }
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        try {
            empleado = new Empleado(txtCargo.getText(), Integer.parseInt(txtHorasExtras.getText()), txtId.getText(), txtNombre.getText(), txtApellido.getText(), Double.parseDouble(txtPagoPorHora.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Algun parametro no esta bien definido, por favor revisar");
            return;
        }
        if (admEmpleado.noEstaCompleto(empleado)) {
            JOptionPane.showMessageDialog(this, "Falta algún parámetro por llenar, por favor revisa los campos.");
            return;
        }
        boolean agregado = admEmpleado.añadirEmpleado(empleado);
        if (agregado == true) {
            JOptionPane.showMessageDialog(this, "Se agrego correctamente");
            mostrarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Ya se encuentra alguien con el mismo ID");
        }
        limpiarDespuesDeAgregar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int filaSeleccionada = tblEmpleado.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor seleccione una fila");
        } else {
            admEmpleado.eliminarEmpleado(filaSeleccionada);
            JOptionPane.showMessageDialog(this, "Eliminado correctamente");
            mostrarTabla();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String inputId = JOptionPane.showInputDialog(null, "Ingrese ID:");
        Empleado empleado = admEmpleado.buscar(inputId);
        if (empleado != null) {

            JOptionPane.showMessageDialog(this, empleado.toString());
        } else {
            JOptionPane.showMessageDialog(null, "Empleado no encontrado con ID: " + inputId, "No encontrado", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed
    private void mostrarTablaOrderna() {
        modelo.setRowCount(0);
        List<Empleado> lista = admEmpleado.obtenerEmpleados().stream().sorted().collect(Collectors.toCollection(ArrayList::new));
        for (Empleado em : lista) {
            Object[] fila = {em.getId(), em.getNombre(), em.getApellido(), em.getPagoPorHora(), em.getCargo(), em.getHorasExtras(), em.calcularSalarioFinal(), em.getNivelCansancio()};
            modelo.addRow(fila);
        }
    }
    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        mostrarTablaOrderna();
    }//GEN-LAST:event_btnOrdenarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblEmpleado;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtHorasExtras;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPagoPorHora;
    // End of variables declaration//GEN-END:variables
}
