/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GestionDeProductosEmpleadoV1;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.stream.Collectors;

/**
 *
 * @author gerardo
 */
public class FrmInsumo extends javax.swing.JInternalFrame {

    DefaultTableModel modelo1;
    Insumo insumo;
    AdministrarInsumo admInsumo;

    /**
     * Creates new form FrmInsumo
     */
    public FrmInsumo() {
        initComponents();
        String[] columna = {"ID", "Nombre", "Cantidad", "Unidades", "Fecha de vencimineto"};
        modelo1 = new DefaultTableModel(columna, 0);
        tblInsumo.setModel(modelo1);
        admInsumo = new AdministrarInsumo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtFechaVencimineto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInsumo = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        cbUnidades = new javax.swing.JComboBox<>();
        btConsultar = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblTitulo.setText("Gestion de insumos");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 27, 221, -1));

        txtCantidad.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad:"));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 85, 156, -1));

        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre:"));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 139, 250, -1));

        txtId.setBorder(javax.swing.BorderFactory.createTitledBorder("ID:"));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 85, 94, -1));

        txtFechaVencimineto.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de vencimiento:"));
        getContentPane().add(txtFechaVencimineto, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 139, 156, -1));

        tblInsumo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblInsumo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 199, 582, -1));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-add-50.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 50, 50));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-minus-48.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 160, -1));

        cbUnidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccionar-", "Kg", "g", "Litros", "Unidades" }));
        cbUnidades.setBorder(javax.swing.BorderFactory.createTitledBorder("Unidades:"));
        getContentPane().add(cbUnidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 83, 153, -1));

        btConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-question-48.png"))); // NOI18N
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 70, 50));

        btnOrdenar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-sort-50.png"))); // NOI18N
        btnOrdenar.setText("Ordenar");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });
        getContentPane().add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 160, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Gemini_Generated_Image_lbvn05lbvn05lbvn.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void mostrarTabla() {
        modelo1.setRowCount(0);
        ArrayList<Insumo> listaInsumos = admInsumo.obtenerInsumos();
        for (Insumo in : listaInsumos) {
            Object[] fila = {in.getId(), in.getNombre(), in.getCantidad(), in.getUnidades(), in.getFechaDeVencimiento()};
            modelo1.addRow(fila);
        }
    }

    private void mostrarTablaOrderna() {
        modelo1.setRowCount(0);
        ArrayList<Insumo> listaOrdenada = admInsumo.obtenerInsumos().stream().sorted().collect(Collectors.toCollection(ArrayList::new));
        for (Insumo in : listaOrdenada) {
            Object[] fila = {in.getId(), in.getNombre(), in.getCantidad(), in.getUnidades(), in.getFechaDeVencimiento()};
            modelo1.addRow(fila);
        }
    }

    private void limpiarDatosDespuesDeAgregar() {
        txtCantidad.setText("");
        txtFechaVencimineto.setText("");
        txtId.setText("");
        txtNombre.setText("");
        cbUnidades.setSelectedIndex(0);
    }
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        try {
            insumo = new Insumo(Double.parseDouble(txtCantidad.getText()), txtNombre.getText(), txtId.getText(), txtFechaVencimineto.getText(), cbUnidades.getSelectedItem().toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Algun parametro no esta bien definido, por favor revisar");
            return;
        }
        if (admInsumo.noEstaCompleto(insumo)) {
            JOptionPane.showMessageDialog(this, "Falta algún parámetro por llenar, por favor revisa los campos.");
            return;
        }

        boolean agregado = admInsumo.añadirInsumo(insumo);
        if (agregado == true) {
            JOptionPane.showMessageDialog(this, "Se agrego correctamente");
            mostrarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Ya se encuentra alguien con el mismo ID");
        }
        limpiarDatosDespuesDeAgregar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int filaSeleccionada = tblInsumo.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor seleccione una fila");
        } else {
            admInsumo.eliminarInsumo(filaSeleccionada);
            JOptionPane.showMessageDialog(this, "Eliminado correctamente");
            mostrarTabla();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed

        String inputId = JOptionPane.showInputDialog(null, "Ingrese ID:");
        Insumo insumo = admInsumo.buscar(inputId);
        if (insumo != null) {

            JOptionPane.showMessageDialog(this, insumo.toString());
        } else {
            JOptionPane.showMessageDialog(null, "Insumo no encontrado con ID: " + inputId, "No encontrado", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed

        mostrarTablaOrderna();

    }//GEN-LAST:event_btnOrdenarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JComboBox<String> cbUnidades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblInsumo;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtFechaVencimineto;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
