/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GestionDeProductosEmpleadoV1;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.util.Set;
import javax.swing.JOptionPane;
import java.util.List;

/**
 *
 * @author gerardo
 */
public class FrmPostre extends javax.swing.JInternalFrame {

    DefaultTableModel modelo;
    Deposito deposito;

    /**
     * Creates new form FrmPostre
     */
    public FrmPostre() {
        initComponents();
        String[] columna = {"Nombre", "Precio", "Stock"};
        modelo = new DefaultTableModel(columna, 0);
        tblPostre.setModel(modelo);
        deposito = new Deposito();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPostre = new javax.swing.JTable();
        btnGenerar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        txtStock = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnOrdenarStock = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 153, 153));
        lblTitulo.setText("Gestion de Postres");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 6, -1, -1));

        txtPrecio.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio:"));
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 49, 146, -1));

        tblPostre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPostre);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 376, 456));

        btnGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-add-50.png"))); // NOI18N
        btnGenerar.setText("Añadir al almacen");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 200, -1));

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-question-48.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 200, -1));

        txtStock.setBorder(javax.swing.BorderFactory.createTitledBorder("Stock:"));
        getContentPane().add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 49, 124, -1));

        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre:"));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 49, 94, -1));

        btnOrdenarStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-sort-50.png"))); // NOI18N
        btnOrdenarStock.setText("Ordenar por stock");
        btnOrdenarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarStockActionPerformed(evt);
            }
        });
        getContentPane().add(btnOrdenarStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 200, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/20250709_0020_Dulces Delicias_simple_compose_01jzpswcexfxzax8k1b2tq43zh.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void mostrarTablaOrdernada() {
        modelo.setRowCount(0);
        Set<String> listaproductos = deposito.productos();
        List<Object[]> filas = new ArrayList();
        for (String producto : listaproductos) {
            Object[] fila = {producto, deposito.precio(producto), deposito.stock(producto)};
            filas.add(fila);
        }
        filas.stream()
                .sorted((f1, f2) -> Integer.compare((int) f1[2], (int) f2[2]))
                .forEach(fila -> modelo.addRow(fila));
    }
    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        deposito.addProduct(txtNombre.getText(), Integer.parseInt(txtPrecio.getText()), Integer.parseInt(txtStock.getText()));
        limpiar();
        mostrarTabla();
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        String inputNombre = JOptionPane.showInputDialog(null, "Ingrese Nombre:");
        String ans = deposito.buscar(inputNombre);
        if (ans != null) {

            JOptionPane.showMessageDialog(this, ans);
        } else {
            JOptionPane.showMessageDialog(null, "Producto no encontrado con Nombre: " + inputNombre, "No encontrado", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnOrdenarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarStockActionPerformed
        // TODO add your handling code here:
        mostrarTablaOrdernada();
    }//GEN-LAST:event_btnOrdenarStockActionPerformed
    private void mostrarTabla() {
        modelo.setRowCount(0);
        Set<String> listaproductos = deposito.productos();
        for (String producto : listaproductos) {
            Object[] fila = {producto, deposito.precio(producto), deposito.stock(producto)};
            modelo.addRow(fila);
        }
    }
    private void limpiar(){
        txtNombre.setText("");
        txtPrecio.setText("");
        txtStock.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnOrdenarStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblPostre;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
